### ISSUE TITLE
Per-project executable setting

### ISSUE THREAD

**Issue by ajmichels** [SublimeLinter/SublimeLinter-phpcs#10]
According to @aparajita in https://github.com/SublimeLinter/SublimeLinter3/issues/32#issuecomment-30882042 each linter package needs "to add an “executable” setting... that would be honored per-project".

It would be great if we could get that support in this package.

Being able to specify something like this in project settings would be great:

```json
{
    "SublimeLinter": {
        "linters": {
            "phpcs": {
                "bin": "${project}/vendor/bin/phpcs"
            }
        }
    }
}
```

I am working on several projects which use different versions of linters and having this support is critical as updating the global settings or my environment PATH every time I switch between projects is not realistic.

**Comment by RushabhJoshi** [comment]
Hi,

Most of the time I am using PSR2 coding standards but sometimes I use WordPress standards.
So I want to specify Wordpress Standards for my WordPress projects

Therefore I use project settings
This is my project settings

```javascript
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings": {
        "SublimeLinter":
        {
            "linters": {
                "phpcs": {
                    "@disable": false,
                    "args": [],
                    "excludes": [],
                    "standard": "WordPress",
                }
            }
        }
    }
}
```

Still this plugin detects PSR2 standards
