### ISSUE TITLE
[Windows] Generating file that fills up hard drive.

### ISSUE THREAD

**Issue by arleslie** [SublimeLinter/SublimeLinter-phpcs#12]
I keep running into an issue randomly where it generates a temp file that eats up my entire harddrive space (68.3GB on last fill up).

If I delete the file it'll instantly reappear, however if I terminate the php and plugin_host process it deletes the file and frees up all space.

I believe it's coming from here as it's running php.exe with `-d auto_append_file="" -d auto_prepend_file="" -d include_path="'C:\tools\pear\\pear'" -f "C:\tools\pear\\phpcs" -- --report=checkstyle --standard=PSR2 "c:\users\andrew~1\appdata\local\temp\SublimeLinter3-Andrew Leslie\PaymentGatewayController.php"`

Here are some logs from Process Monitor that maybe useful, if there are any other logs I can provide for when the issue happens again let me know how to grab those.
CSV: https://arleslie.com/shares/2016-03-14_03-07-24.CSV
PML: https://arleslie.com/shares/2016-03-14_03-07-24.PML

The PML file is loadable via Process Monitor and will provide a lot more information than the CSV.

**Comment by ajmichels** [comment]
I am wondering if this issue is some how related to SublimeLinter/SublimeLinter-php#12

Can you try creating a file (bad-file.php) that has just the following for contents:

```
<?php
foreach
```

and then run the following command against it:

`php.exe -d auto_append_file="" -d auto_prepend_file="" -d include_path="'C:\tools\pear\\pear'" -f "C:\tools\pear\\phpcs" -- --report=checkstyle --standard=PSR2 "bad-file.php"`

See if that results in your continuously growing temp file.

**Comment by arleslie** [comment]
Test file does not appear to cause the issue but the php process never terminates.

```
[04:42:13][C:\Users\Andrew Leslie\Documents|53]# php.exe -d auto_append_file="" -d auto_prepend_file="" -d include_path="'C:\tools\pear\\pear'" -f "C:\tools\pear\\phpcs" -- --report=checkstyle --standard=PSR2 .\test.php
PHP Notice:  Undefined offset: 2 in C:\tools\pear\pear\PHP\CodeSniffer\Standards\AbstractPatternSniff.php on line 448
PHP Notice:  Undefined offset: 3 in C:\tools\pear\pear\PHP\CodeSniffer\Standards\AbstractPatternSniff.php on line 455
PHP Notice:  Undefined offset: 2 in C:\tools\pear\pear\PHP\CodeSniffer\Standards\AbstractPatternSniff.php on line 461
PHP Notice:  Undefined offset: 2 in C:\tools\pear\pear\PHP\CodeSniffer\Standards\AbstractPatternSniff.php on line 489
PHP Notice:  Undefined index: parenthesis_closer in C:\tools\pear\pear\PHP\CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff.php on line 77
PHP Notice:  Undefined offset: -1 in C:\tools\pear\pear\PHP\CodeSniffer\Standards\Squiz\Sniffs\ControlStructures\ForEachLoopDeclarationSniff.php on line 98
```

**Comment by arleslie** [comment]
Alright, I have managed to reproduce it repeatedly.

You need to have the SFTP plugin by wbond installed.

Setup an SFTP mapping and set upload_on_save to true.
Create a syntax error and save it multiple times before the linter runs to where you get the dialog prompt from the SFTP plugin ("Thanks for trying").
When clicking cancel it'll cause the process to loop and create the file.

**Comment by ajmichels** [comment]
Interesting. I am not familiar with the SFTP package so I will have to spend some time looking into to that. I don't have a Windows machine either so it will be a little slow going for me to diagnose what is going on. 

Does this issue happen when you disable the SFTP package? Also, can you do the following:

1. Put SublimeLinter into [Debug Mode](http://www.sublimelinter.com/en/latest/troubleshooting.html#debug-mode)
2. open the console view in [Sublime](http://docs.sublimetext.info/en/latest/basic_concepts.html?highlight=console#sublime-text-is-programmable)
3. Reproduce this issue
4. Copy all of the debug output and paste it here, or make a [gist](https://gist.github.com) and provide a link.

**Comment by arleslie** [comment]
This does happen with the SFTP plugin disabled so it is not required.

The key is to save the file before the linter completes it seems.

There is no debug output until I terminate the php.exe process.

I reproduced it twice and both are here: https://gist.github.com/arleslie/00559dd4713ce4a73a2f

**Comment by arleslie** [comment]
It appears when terminating the PHP process when this bug occurs results in plugin_host.exe using all available ram.

**Comment by braver** [comment]
Can anyone verify if this still happens with SublimeLinter 4?

**Comment by kaste** [comment]
We switched to stdin linting, so I'm closing.
