### ISSUE TITLE
Problem to locate the `phpcs` binary if the default files can't be located

### ISSUE THREAD

**Issue by shulard** [SublimeLinter/SublimeLinter-phpcs#14]
Hello !

I've encountered a tiny issue in the morning with the PHPCS checks.

Here my installation details: 

* ST3 Build 3113
* SublimeLinter: 3.7.4
* SublimeLinter-phpcs: 1.1.0

At load, I got this path details and the warning ... :

```
SublimeLinter: user shell: /bin/zsh 
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/MacGPG2/bin
 
SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs'
```

I created a specific project configuration :

```json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter": {
        "linters": {
            "phpcs": {
                "@disable": false,
                "standard": "${project}/phpcs.xml",
                "cmd": "${project}/bin/phpcs"
            }
        }
    }
}
```

The `phpcs` binary exists in the `cmd` location but not as a default binary (`phpcs` is not available as an executable in my `$PATH`).

I never use the default `phpcs` binary location, do you think it's possible to use the defined `cmd` entry instead of the default one at plugin load ?

**Comment by ajmichels** [comment]
Unfortunately because of how the core SublimeLinter project is set up you need to have it it available in you PATH even if you are going to use a project specific setting. I know that doesn't make sense but I am not a contributor for the SublimeLinter project and I can't tell you why that is.

**Comment by shulard** [comment]
Ok I understand that it's a root project issue 😄.
I'm not a Python dev but I'll open a discussion about that in SublimeLinter.

Thanks for your quick feedback !

**Comment by shulard** [comment]
As a reference, this is the ID of the root project issue: SublimeLinter/SublimeLinter3#455
