### ISSUE TITLE
Trouble using third-party WordPress standard

### ISSUE THREAD

**Issue by ajmichels** [SublimeLinter/SublimeLinter-phpcs#17]
From @RushabhJoshi

> Hi,
> 
> Most of the time I am using PSR2 coding standards but sometimes I use WordPress standards.
> So I want to specify Wordpress Standards for my WordPress projects
> 
> Therefore I use project settings
> This is my project settings
> 
> ```javascript
> {
>     "folders":
>     [
>         {
>             "path": "."
>         }
>     ],
>     "settings": {
>         "SublimeLinter":
>         {
>             "linters": {
>                 "phpcs": {
>                     "@disable": false,
>                     "args": [],
>                     "excludes": [],
>                     "standard": "WordPress",
>                 }
>             }
>         }
>     }
> }
> ```
> Still this plugin detects PSR2 standards

**Comment by ajmichels** [comment]
@RushabhJoshi

Couple of things. First, your SublimeLinter settings are not going to take effect because they should not be defined within the "settings" object, it should be sibling to "settings" and "folders".

Second, can you provide a bit more information regarding were you obtained this WordPress standard and where it is stored on your local system relative to your sublime project file and the root of your project? Are you able to successfully execute `phpcs` manually using this standard? The documentation for doing so can be found [here](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#specifying-a-coding-standard). It would look something like `phpcs --standard=/path/to/WordPress /path/to/code/myfile.php`. Whatever `--standard` path you have to enter for this commend work is the same path you are going to have to put in your project file.

**Comment by RushabhJoshi** [comment]
Worked with the first solution, Thanks.
