### ISSUE TITLE
Option to use tabs instead of spaces for indenting

### ISSUE THREAD

**Issue by Luc45** [SublimeLinter/SublimeLinter-phpcs#20]
I've just read an article from Jeff Atwood, where he mentions a team leader that had the habit of reformating everyone's codes according to his personal taste, and how that was terrible. [1]

I find it annoying to be forced to use spaces for indentation with SublimeLinter, since the war of spaces vs tabs is purely personal. [2]

Can we have an option to choose between spaces or tabs?

[1] https://blog.codinghorror.com/death-to-the-space-infidels/
[2] https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

**Comment by ajmichels** [comment]
This is all a matter of what your settings are for PHPCS which is outside the scope of this project. This project just brings PHPCS functionality into SublimeText. I think you should look into the PHPCS documentation. 

https://github.com/squizlabs/PHP_CodeSniffer/wiki

**Comment by ajmichels** [comment]
@Luc45 On a side note, you seem to have glanced over Jeff's final conclusions regarding the topic of code formatting.

> Choose tabs, choose spaces, choose whatever layout conventions make sense to you and your team. It doesn't actually matter which coding styles you pick. What does matter is that you, and everyone else on your team, sticks with those conventions and uses them consistently.

This means that if you are contributing to a project you should follow the standards defined by the maintainers of that project regardless of your personal preferences. Jeff sights some very reputable sources regarding why this is important. If you are maintaining your own personal project by all means use whatever standards you want. But when you are in someone else's house you need to follow their rules.

Fortunately there are tools out there such as [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) which make it a lot easier for teams to establish a standard for their shared codebase and enforce it.

**Comment by eanbowman** [comment]
It'd be grand if ANYONE could just answer this simple question instead of pointing to links that have reams and reams of text that seem to provide no good answer.

**Comment by eanbowman** [comment]
![image](https://user-images.githubusercontent.com/1637212/78676210-221d1880-78b4-11ea-8642-fd82643153b0.png)
