### ISSUE TITLE
Automatically detect project-specific rulesets

### ISSUE THREAD

**Issue by rmccue** [SublimeLinter/SublimeLinter-phpcs#21]
Sublime Linter supports [automatically searching for rulesets](http://www.sublimelinter.com/en/latest/linter_attributes.html#config-file). It would be great if SublimeLinter-phpcs could support this for a few well-known filenames; namely, `phpcs.xml`, `phpcs.ruleset.xml` and `ruleset.xml` all seem to be commonly used. (`ruleset.xml` is a bit generic, so might be better to not autodetect that.)

**Comment by mathroc** [comment]
phpcs does that automatically if you don’t pass the `--standard` argument, which this plugin does. but you can disable it by setting `"standard": false` in the phpcs configuration block

**Comment by Mat-thieu** [comment]
If you're here because `"standard": false` didn't work, try `"standard": ""`

**Comment by braver** [comment]
Now that we're here, isn't it really weird that this plugin sets a standard by default? Changing it probably breaks people's setups, but I'm all about that anyway 😉 So, let's fix the bug in core, but also clean up this thing here. You've got 24 hours to vote against to stop me.

**Comment by braver** [comment]
see baa8015001df4da8066d41e3e1d8d18bbd6dd56f
