### ISSUE TITLE
Linter no longer working, The file ${args} does not exist...

### ISSUE THREAD

**Issue by metalandcoffee** [SublimeLinter/SublimeLinter-phpcs#29]
Sad face.

I'm really not sure why this error started happening but would love some insight `ERROR: The file "${args}" does not exist.`

![image](https://user-images.githubusercontent.com/20868511/36981444-29fe1346-205b-11e8-9dc8-0238f3250b5e.png)

**Comment by kaste** [comment]
Hm, seems like you did not update SublimeLinter to v4. Is that correct?

**Comment by metalandcoffee** [comment]
Yup, because after the SublimeLinter upgrade - the SublimeLinter-phpcs linter wasn't working anymore so I downgraded to get it working again.

It looks like you guys pushed an update so upon re-upgrading my SublimeLinter to v4, SublimeLinter-phpcs is working now :) Thanks @kaste
