### ISSUE TITLE
Incompatible with Windows

### ISSUE THREAD

**Issue by qaharmdz** [SublimeLinter/SublimeLinter-phpcs#36]
I get this issue recently. If I delete `vendor\bin\phpcs` the linter is working, or I would get error:

    Execution failed
    [WinError 193] %1 is not a valid Win32 application

Even though vendor\bin\phpcs always back whenever I use composer install/update; currently I just delete it manually.

I try to use global phpcs or pointing to the python folder but it's not work.

    "SublimeLinter":
    {
        "linters":
        {
            "phpcs":
            {
                "disable": false,
                "python": "C:\\Users\\MyUser\\AppData\\Local\\Programs\\Python\\Python36-32\\",
                "cmd": "C:\\Users\\MyUser\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcs"
            }
        }
    }

I wonder how to fix this?

**Comment by kaste** [comment]
Hi 👋

Please enable debug and post the command SublimeLinter executes here. Compare that to the command you would run yourself if you were on the command line.

Note that python is not a valid setting here bc you're using php. Also cmd is not a supported setting so it doesn't do anything if you declare it.

**Comment by qaharmdz** [comment]
Hello,

This is the debug message in console

    SublimeLinter: #71 SublimeLinter.sublime-package:703: 'phpcs' is linting 'HttpKernel.php'
    SublimeLinter: #72 SublimeLinter.sublime-package:703: 'php' is linting 'HttpKernel.php'
    SublimeLinter: #71 SublimeLinter.sublime-package:1104: ERROR:   Execution failed

      [WinError 193] %1 is not a valid Win32 application

      F:\Ampps\www\gubug  (working dir)
      > type vendor\symfony\http-kernel\HttpKernel.php | F:\Ampps\www\gubug\vendor\bin\phpcs --report=emacs --stdin-path=F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php --standard=PSR2 -

    SublimeLinter: #72 SublimeLinter.sublime-package:1111: Running ...

      F:\Ampps\www\gubug  (working dir)
      > type vendor\symfony\http-kernel\HttpKernel.php | F:\Ampps\php-7.1\php.exe -l -n -d display_errors=On -d log_errors=Off

    SublimeLinter: #72 SublimeLinter.sublime-package:753: php output:
        No syntax errors detected in -
    SublimeLinter: #72 SublimeLinter.sublime-package:793: php: No match for line: 'No syntax errors detected in -'
    SublimeLinter: SublimeLinter.sublime-package:275: Linting buffer 150 took 0.14s

And when `vendor/bin/phpcs` deleted, use global phpcs

    SublimeLinter: #75 SublimeLinter.sublime-package:703: 'phpcs' is linting 'HttpKernel.php'
    SublimeLinter: #76 SublimeLinter.sublime-package:703: 'php' is linting 'HttpKernel.php'
    SublimeLinter: #75 SublimeLinter.sublime-package:1111: Running ...

      F:\Ampps\www\gubug  (working dir)
      > type vendor\symfony\http-kernel\HttpKernel.php | C:\Users\Qahar\AppData\Roaming\Composer\vendor\bin\phpcs.bat --report=emacs --stdin-path=F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php --standard=PSR2 -

    SublimeLinter: #76 SublimeLinter.sublime-package:1111: Running ...

      F:\Ampps\www\gubug  (working dir)
      > type vendor\symfony\http-kernel\HttpKernel.php | F:\Ampps\php-7.1\php.exe -l -n -d display_errors=On -d log_errors=Off

    SublimeLinter: #76 SublimeLinter.sublime-package:753: php output:
        No syntax errors detected in -
    SublimeLinter: #76 SublimeLinter.sublime-package:793: php: No match for line: 'No syntax errors detected in -'
    SublimeLinter: #75 SublimeLinter.sublime-package:753: phpcs output:
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:46:195: warning - Line exceeds 120 characters; contains 195 characters
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:112:15: warning - Line exceeds 120 characters; contains 135 characters
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:133:159: warning - Line exceeds 120 characters; contains 159 characters
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:177:15: warning - Line exceeds 120 characters; contains 137 characters
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:212:15: warning - Line exceeds 120 characters; contains 138 characters
        F:\Ampps\www\gubug\vendor\symfony\http-kernel\HttpKernel.php:233:144: warning - Line exceeds 120 characters; contains 144 characters
    SublimeLinter: SublimeLinter.sublime-package:275: Linting buffer 150 took 0.97s

As you can see, the different is the command from where phpcs is executed.

**Comment by kaste** [comment]
The difference is that we don't add .bat to the executable. So it seems the SublimeLinter core ComposerLinter doesn't support Windows. Thanks, you found a bug.

You can workaround here by setting executable to $folder\\vendor\\bin\\phpcs.bat

**Comment by marcelo2605** [comment]
I'm having the same error (Windows too).

```
"SublimeLinter": {
    "linters": {
        "phpcs": {
        	"@disable": false,
            "standard": "${folder}\\phpcs.xml",
            "cmd": "${folder}\\vendor\\bin\\phpcs.bat"
        }
    }
}
```

> Execution failed
> 
>   [WinError 193] %1 is not a valid Win32 application
> 
>   M:\vagrant-local\www\test-website\public_html\wp-content\themes\test-website  (working dir)
>   type app\controllers\app.php | M:\vagrant-local\www\test-website\public_html\wp-content\themes\test-website\vendor\bin\phpcs --report=emacs --standard=M:\vagrant-local\www\test-website\public_html\wp-content\themes\test-website\phpcs.xml --stdin-path=M:\vagrant-local\www\test-website\public_html\wp-content\themes\test-website\app\controllers\app.php -

**Comment by kaste** [comment]
Okay I made a fix, but we need testers. PR is https://github.com/SublimeLinter/SublimeLinter/pull/1374


1. Find your Packages Folder (Preferences > Browse Packages)
2. Open this folder with `cmd`
3. `git clone https://github.com/SublimeLinter/SublimeLinter.git`
4. `git checkout iterate-composer-linter` 
5. Restart Sublime

After testing, you can just delete the SublimeLinter folder you created in step 3

**Comment by marcelo2605** [comment]
@kaste, before step 4, I need to enter SublimeLinter folder to run `git checkout iterate-composer-linter`, right?

Here is the console:

> Linter crashed.
> 
> Traceback (most recent call last):
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\backend.py", line 87, in execute_lint_task
>     errors = linter.lint(code, view_has_changed, settings) or []
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 726, in lint
>     return self.parse_output(output, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 747, in parse_output
>     return self.parse_output_via_regex(output, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 767, in parse_output_via_regex
>     error = self.process_match(m, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 848, in process_match
>     start, end = vv.full_line(m.line)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 83, in full_line
>     start = self._newlines[line]
> IndexError: list index out of range

**Comment by kaste** [comment]
Hm, I don't like tracebacks but this one could at least mean that it executed the command. Can we call this progress. 🤣

Can you enable debug in the user settings. Let's see what cmd SublimeLinter here executes.

**Comment by kaste** [comment]
Yes you need to `cd` into that folder. Updated the guide.

Regarding that error: Basically it means the linter is reporting errors on lines not present in the view. (Say it reports an error on line 100, but your file only has 55 lines.) Maybe the output parsing has a defect, or the linter reports some errors coming from other files as well. But, at least it reports some errors.

**Comment by kaste** [comment]
Another comment:

```
            "standard": "${folder}\\phpcs.xml",
            "cmd": "${folder}\\vendor\\bin\\phpcs.bat"
```

`cmd` is not a valid setting for this linter, so it basically doesn't do anything. `standard`, not completely sure, but https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#specifying-a-coding-standard should point to a folder or just a named standard like `PEAR`

**Comment by marcelo2605** [comment]
Hi @kaste, here was I got enabling the debug:

> DPI scale: 1
> startup, version: 3143 windows x64 channel: stable
> executable: /C/Program Files/Sublime Text 3/sublime_text.exe
> working dir: /C/Program Files/Sublime Text 3
> packages path: /C/Users/marce/AppData/Roaming/Sublime Text 3/Packages
> state path: /C/Users/marce/AppData/Roaming/Sublime Text 3/Local
> zip path: /C/Program Files/Sublime Text 3/Packages
> zip path: /C/Users/marce/AppData/Roaming/Sublime Text 3/Installed Packages
> ignored_packages: ["Vintage"]
> generating syntax summary
> Errors parsing theme:
> icon_folder_loading is missing layer0.opacity, setting to 1.0 for backwards compatibility
> icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
> pre session restore time: 0.41781
> startup time: 0.47081
> first paint time: 0.47081
> no such context .string-single in Packages/SCSS/SCSS.tmLanguage
> no such context .string-double in Packages/SCSS/SCSS.tmLanguage
> no such context .media-query-list in Packages/SCSS/SCSS.tmLanguage
> no such context .string-double in Packages/SCSS/SCSS.tmLanguage
> no such context .string-single in Packages/SCSS/SCSS.tmLanguage
> no such context .media-query-list in Packages/SCSS/SCSS.tmLanguage
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin Default.ui
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-pygments
> reloading plugin 0_package_control_loader.50-dateutil
> reloading plugin 0_package_control_loader.50-markupsafe
> reloading plugin 0_package_control_loader.50-python-markdown
> reloading plugin 0_package_control_loader.51-python-jinja2
> reloading plugin 0_package_control_loader.55-jsonschema
> reloading plugin 0_package_control_loader.55-mdpopups
> reloading plugin A File Icon.A File Icon
> reloading plugin Boxy Theme.BT
> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
>     m = importlib.import_module(modulename)
>   File "./python3.3/importlib/__init__.py", line 90, in import_module
>   File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
>     exec(compile(source, source_path, 'exec'), mod.__dict__)
>   File "BT in C:\Users\marce\AppData\Roaming\Sublime Text 3\Installed Packages\Boxy Theme.sublime-package", line 1, in <module>
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
>     exec(compile(source, source_path, 'exec'), mod.__dict__)
>   File "utils in C:\Users\marce\AppData\Roaming\Sublime Text 3\Installed Packages\Boxy Theme.sublime-package", line 4, in <module>
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
>     exec(compile(source, source_path, 'exec'), mod.__dict__)
>   File "utils.config in C:\Users\marce\AppData\Roaming\Sublime Text 3\Installed Packages\Boxy Theme.sublime-package", line 9, in <module>
>   File "C:\Users\marce\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 27, in <module>
>     from . import frontmatter
>   File "C:\Users\marce\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\frontmatter.py", line 2, in <module>
>     import yaml
> ImportError: No module named 'yaml'
> reloading plugin Boxy Theme.Icons
> reloading plugin EditorConfig.EditorConfig
> reloading plugin Emmet.emmet-plugin
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin SCSS.scss_completions
> reloading plugin SublimeLinter-phpcs.linter
> reloading plugin SublimeLinter.__init__
> reloading plugin SublimeLinter.active_linters_view
> reloading plugin SublimeLinter.busy_indicator_view
> reloading plugin SublimeLinter.goto_commands
> reloading plugin SublimeLinter.highlight_view
> reloading plugin SublimeLinter.log_handler
> reloading plugin SublimeLinter.message_view
> reloading plugin SublimeLinter.panel_view
> reloading plugin SublimeLinter.status_bar_view
> reloading plugin SublimeLinter.sublime_linter
> reloading plugin Xdebug Client.main
> reloading plugin PlainTasks.APlainTasksCommon
> reloading plugin PlainTasks.PlainTasks
> reloading plugin PlainTasks.PlainTasksDates
> reloading plugin PlainTasks.PlainTasksToHTML
> reloading plugin PlainTasks.plist_parser
> plugins loaded
> SublimeLinter: log_handler.py:74: Logging installed; log level INFO
> SublimeLinter: sublime_linter.py:43: debug mode: on
> SublimeLinter: sublime_linter.py:44: version: 4.4.1
> SublimeLinter: sublime_linter.py:240: Delay buffer 29 for 0.3s
> SublimeLinter: sublime_linter.py:240: Delay buffer 32 for 0.3s
> Emmet: No need to update PyV8
> Package Control: Skipping automatic upgrade, last run at 2018-05-04 06:25:01, next run at 2018-05-04 07:25:01 or after
> SublimeLinter: sublime_linter.py:240: Delay buffer 30 for 0.3s
> SublimeLinter: sublime_linter.py:363: detected syntax: html
> SublimeLinter: #1 linter.py:703: 'phpcs' is linting 'page-a-alle-idiomas.php'
> SublimeLinter: #1 linter.py:1125: Running ...
> 
>   M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas  (working dir)
>   > type app\controllers\page-a-alle-idiomas.php | M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\vendor\bin\phpcs.BAT --report=emacs --stdin-path=M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\controllers\page-a-alle-idiomas.php --standard=M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\phpcs.xml -
> 
> SublimeLinter: #1 linter.py:756: phpcs output:
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\resources\functions.php:1:1: error - End of line character is invalid; expected "\n" but found "\r\n" (Generic.Files.LineEndings.InvalidEOLChar)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\controllers\app.php:88:133: warning - Line exceeds 120 characters; contains 133 characters (Generic.Files.LineLength.TooLong)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\controllers\app.php:97:130: warning - Line exceeds 120 characters; contains 130 characters (Generic.Files.LineLength.TooLong)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\controllers\page-a-alle-idiomas.php:9:40: error - Opening brace should be on a new line (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\controllers\page-contato.php:9:34: error - Opening brace should be on a new line (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\filters.php:122:141: warning - Line exceeds 120 characters; contains 141 characters (Generic.Files.LineLength.TooLong)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\helpers.php:1:1: error - End of line character is invalid; expected "\n" but found "\r\n" (Generic.Files.LineEndings.InvalidEOLChar)
>     M:\vagrant-local\www\alle-idiomas\public_html\wp-content\themes\alle-idiomas\app\setup.php:14:143: warning - Line exceeds 120 characters; contains 143 characters (Generic.Files.LineLength.TooLong)
> SublimeLinter: #1 __init__.py:1273: ERROR: Linter crashed.
> 
> Traceback (most recent call last):
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\backend.py", line 87, in execute_lint_task
>     errors = linter.lint(code, view_has_changed, settings) or []
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 726, in lint
>     return self.parse_output(output, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 747, in parse_output
>     return self.parse_output_via_regex(output, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 767, in parse_output_via_regex
>     error = self.process_match(m, virtual_view)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 848, in process_match
>     start, end = vv.full_line(m.line)
>   File "C:\Users\marce\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 83, in full_line
>     start = self._newlines[line]
> IndexError: list index out of range
> SublimeLinter: sublime_linter.py:286: Linting buffer 30 took 0.55s
>

**Comment by marcelo2605** [comment]
@kaste Thanks. I will try this later and back if got success

**Comment by joelcollyer** [comment]
I had the same error come up when we installed PHPCS as a composer dependency in a project (I previously had it installed globally, and it worked fine).

Some helpful soul pointed out that you need to add `.bat` to the end of your php linter executable string as Windows has a hard time resolving the symbolic link.

Here's the fix that worked for me under `Preferences > Package Settings > Sublime Linter > Settings`:
```
// SublimeLinter Settings - User
{
    "linters": {
        "phpcs":{
            "executable": "${folder}\\vendor\\bin\\phpcs.bat"
        }
    }
}
```
