### ISSUE TITLE
excluding a pattern doesn't work

### ISSUE THREAD

**Issue by Skarlso** [SublimeLinter/SublimeLinter-phpcs#41]
Hi.

In #19 it was discussed that the exclusion pattern isn't working. The issue was closed with something like switched to something else and it should resolve the issue. 

But it did not. I'm trying to exclude a number of files like this: 

```json
		"phpcs":
		{
			"standard": "./phpcs.xml",
			"excludes": [
				"*/a.php",
				"*/b.php"
			]
		},
```

But the files are still linted no matter what I do.

Is there another solution for this?

Thanks!

**Comment by kaste** [comment]
Hi!

Are the exclude patterns you show above mocked up? Bc I cannot reproduce this with your settings.

**Comment by Skarlso** [comment]
Hi! 

What do you mean by mocked up? Well, I didn't use the actual filenames, but basically this is what I'm using for actual files. 'a' and 'b' are just files that I have in the project under different names. Like, login.php or index.php or whatever. :)

Either way, that is interesting. It still lints for me. :/ I'm not sure what I might be missing.

**Comment by kaste** [comment]
I don't see what's missing here either. Can you enable debug mode in the settings and look if it actually applies the standard setting? Maybe post your settings here.

The function we're using here is `fnmatch`.  You could open the Sublime Console and then

```
> from fnmatch import fnmatch
> fnmatch('/path/to/a.php', '*/a.php')  # (filename, pattern)
True
```

If it returns `True` it means the file will be excluded.

**Comment by Skarlso** [comment]
So, should I use full path instead of glob is what you're saying?

**Comment by Skarlso** [comment]
cause this returns False:

```
>>> fnmatch('/Users/user/test-project', '*/a.php')
False
```

Where `a.php` is under `test-project/temp` folder.

**Comment by Skarlso** [comment]
Oh, I was missing the file name at the end.

**Comment by kaste** [comment]
In the Sublime console you can use

```
fnmatch(view.file_name(), '*/a.php')
```

to test any of your patterns against the file name of the last active view.

**Comment by Skarlso** [comment]
Yeah that works. That returns True on the file. What the hell. Why is it still linting?

**Comment by kaste** [comment]
These are _exclude_ patterns, any match will exclude that file.

**Comment by Skarlso** [comment]
OMFG. I've put these settings into User settings and not Linter settings. :/ :( 👎

**Comment by Skarlso** [comment]
Lovely. Now it works. Well... Thanks for sticking with me on this ride man. :)

**Comment by kaste** [comment]
🎉
