### ISSUE TITLE
The linter ignores .phtml files

### ISSUE THREAD

**Issue by iodic** [SublimeLinter/SublimeLinter-phpcs#43]
I am working on a Magento project and the linter is not running for `.phtml` files.

These are my settings for PHPCS:

```
"phpcs":
{
	"@disable": false,
	"args": "--standard=Magento",
	"excludes": []
}
```

If I add: `"selector": "source.phtml, source.php"`, it keeps reporting "No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.". It does this for `.php` files; for `.phtml` files it still has no output.

If I set the standard to WordPress and open a WordPress project it works fine with the above settings.

Any help would be greatly appreciated!

Thanks,
Marko

**Comment by kaste** [comment]
I don't know if I can be of any help here, but at least for the default Sublime syntaxes ... I don't think there is actually a `source.phtml` selector bc there is no real difference between 'phtml' and 'php'. 

If you want to *select the whole file* and send it to the linter I would use either `embedding.php` or `text.html.basic` (the latter is of course true for all html files). The selector `source.php` only grabs/selects portions of the file. E.g.

```
<?php $first = true; foreach($examples as $lang => $code):?>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ source.php
```

🤞

**Comment by iodic** [comment]
Thanks a lot for replying! (And sorry about my late feedback.)

This seems to be working. I will test it a bit more but it seems to have helped. 🤘
