### ISSUE TITLE
Errors don't show

### ISSUE THREAD

**Issue by p4scu41** [SublimeLinter/SublimeLinter-phpcs#46]
When I run `Lint this view` the errors don't show, just show the warnings, but if I run phpcs in command line it shows all errors. I activated the debug mode but nothing shows in the console.

![image](https://user-images.githubusercontent.com/1633236/58977814-17738d80-8790-11e9-9f0d-828299f90055.png)

![image](https://user-images.githubusercontent.com/1633236/58977782-0296fa00-8790-11e9-9560-fc5c6d21c86f.png)

![image](https://user-images.githubusercontent.com/1633236/58978039-98cb2000-8790-11e9-8686-8eec00715707.png)

![image](https://user-images.githubusercontent.com/1633236/58978575-b947aa00-8791-11e9-9231-be98f9b27414.png)

`PHP_CodeSniffer version 3.4.2 (stable) by Squiz (http://www.squiz.net)`

```JSON
// SublimeLinter Settings - User
{
    "linters": {
        "php": {
            "disable": false,
            "args": "-l",
            "executable": "/usr/bin/php",
            "lint_mode": "save",
            "selector": "source.php"
        },
        "phpcs": {
            "disable": false,
            "filter_errors": [],
            "args": "--standard=PSR2",
            "executable": "/home/usuario/.config/composer/vendor/bin/phpcs",
            "lint_mode": "save",
            "selector": "source.php"
        },
        "phpmd": {
            "disable": false,
            "args": [],
            "executable": "/home/usuario/.config/composer/vendor/bin/phpmd",
            "lint_mode": "save",
            "selector": "source.php",
            "rulesets": "cleancode,codesize,controversial,design,naming,unusedcode"
        }
    }
}
```

**Comment by kaste** [comment]
Hi! The output hear indicates that you're not sending the whole files to the linter but only the parts between the PHP tags. 

I noticed you set selector in the settings. Can you try the default setting? (The default is not the empty string but not setting anything at all.)

**Comment by p4scu41** [comment]
yeah, it works. I misunderstood the `selector`, I thought it refers to the file extension. 

Thanks kaste for your quick answer.

**Comment by kaste** [comment]
👌
