### ISSUE TITLE
phpcs: no output - all settings seems fine

### ISSUE THREAD

**Issue by hanoii** [SublimeLinter/SublimeLinter-phpcs#48]
I don't quite get this - after managing to install it as I wanted to, I am getting no output erros:

```
SublimeLinter: #3 linter.py:900       phpcs: wanted executable is '/Users/ariel/.composer/vendor/bin/phpcs'
SublimeLinter: #3 linter.py:1636      Running ...

  /Users/ariel/Sites/brooksdigital/options  (working dir)
  $ cat modules/contrib/google_calendar/google_calendar.module | /Users/ariel/.composer/vendor/bin/phpcs --report=emacs --extensions=php,module,test,inc --standard=Drupal,DrupalPractice --stdin-path=/Users/ariel/Sites/brooksdigital/options/modules/contrib/google_calendar/google_calendar.module -

SublimeLinter: #3 linter.py:1196      phpcs: no output
SublimeLinter: sublime_linter.py:575  Linting 'google_calendar.module' took 0.59s
```

no error, `just phpcs: no output`. 

If I run that same exact command: `cat modules/contrib/google_calendar/google_calendar.module | /Users/ariel/.composer/vendor/bin/phpcs --report=emacs --extensions=php,module,test,inc --standard=Drupal,DrupalPractice --stdin-path=/Users/ariel/Sites/brooksdigital/options/modules/contrib/google_calendar/google_calendar.module -` in the console, I do get errors on the output

I am running the latest of everything, on OSX catalina.

**Comment by kaste** [comment]
😒 

You probably did run this from the correct working dir bc that usually matters e.g. for finding config files etc.

Now, you set `executable` on your own which probably means the plugin couldn't detect it automatically and you tried to fix that which in turn could mean that the environment differs between inside Sublime and inside your shell.  

That would basically be my first shot into the dark: If you copied the command verbatim to your shell plus the working dir is the same; what's hidden is still the whole ENV, PATH etc. thing.  All the composer stuff that gets setup for a login shell.  (E.g. `COMPOSER_HOME`.)

The best test for this is to *close all Sublime*, then start a normal shell where everything works and start Sublime via `subl .`.  Sublime should now inherit the exact ENV from the shell you started it from. 

So these are my first ideas: TLDR; Did you had problems/errors before setting `executable` then maybe these need to be fixed.

**Comment by hanoii** [comment]
@kaste I tried running it with `subl .` and it's the same.

The reason I set my own executable is that it was picking up the local one from a composer package on the project and I wanted to use the global one with all the different standards I have configured. And all seems to work just fine to be honest, and there's no error or anything, just no output. Extensions are there and all.

**Comment by hanoii** [comment]
Interestingly odd.

This is my configuration:

```
  "linters": {
        "phpcs":
        {
            // "selector": "source.php, source.module, source.inc, source.test",
            "executable": "/Users/ariel/.composer/vendor/bin/phpcs",
            "args": ["--extensions=php,module,test,inc"]
        },
    }
```

on top of some specifics to the project.

Notice the selectors commented out. With that **not commented,** this issue happens. With the selectors not configured, it now works.

**Comment by kaste** [comment]
Ookay. I'm actually super-stupid with these syntax selectors but that basically means `text.html.basic` (part of the default selector) is the main, correct selector for you. (But sure `source.module` and `source.inc`, are these real?)

What I hate a bit is the logging lie `cat xxx | ` although it looks like we only sent a small portion of that file. (Of course, I don't know *what* we actually extract for the linter because I don't know what your selector selects. I have my https://github.com/kaste/HighlightScopes to help me with that.)

**Comment by hanoii** [comment]
Ok, so I understood the selectors in the wrong way. I thought they were related to file extensions. It's true that .module and .inc are wrong as they are not there, but should they disable or prevent those about source.php being found?

**Comment by kaste** [comment]
No, `"source.php, foo"` is okay. The `, ` is a set union op. (A trailing comma though is catastrophic because its the union with the empty string and just selects all files, all views.)  

But for this example php file with the builtin syntax, `source.php` only selects

![image](https://user-images.githubusercontent.com/8558/72933684-7a875400-3d62-11ea-895f-d9f5d0f6155d.png)

but `text.html.basic` selects the whole file.  I wonder why phpcs does give nothing for that.

**Comment by hanoii** [comment]
what's the default? and how does tied to the the `cat` command and phpcs? I wonder why with the one I configured didn't work. I am just trying it with plain PHP files

**Comment by kaste** [comment]
The default is basically the source.php part plus the html selector I posted above. See the source code for the details. For "normal" PHP files the html selector is the important one.

With selectors we decide which views or parts of the views we send to the linter. Your patched selector did not select the whole source file, so the log lied, it should have printed cat part of file.php or something like that.
