### ISSUE TITLE
Find phpcs.xml in parent directory/directories

### ISSUE THREAD

**Issue by joemottershaw** [SublimeLinter/SublimeLinter-phpcs#49]
Trying to get this package to look for a `phpcs.xml` config file in parent directories, an example of this would be when we work with WordPress using Local by FlyWheel.

This creates a project directory tree of:

```
- project_name
  - app
    - public
      - wp-admin
      - wp-content
        - plugins
        - themes   
      - wp-includes
    - sql
  - config
  - logs
```

We have boilerplate repo's for themes and plugins which we clone in for a project, I want a `phpcs.xml` file in each of those repos, so when they are pull/cloned in, any file within that repo/directory just automatically has a config file, but it doesn't seem to work. I was under the impression phpcs would first look in the directory of the currently opened file and if it doesn't have a config file then it work it's way back up through the directories until it gets to the plugin or theme repo/directory or default to the PEAR standard.

I know we could just create a new wordpress project and manually place the config file in the project root, but it just keeps it outside the scope of where we want them.

If I put the config file in `project_name` (project root directory), it finds it. I can tell this as the standard is set to PSR2 in my config file. However, as soon as I move the config file to say `wp-content` to test this, the standard reverts back to PEAR (default) even though the config file is still in a parent/ancestor directory to the currently opened file.

I'm assuming this is working in the project root as it looks there first, so I'm assuming I need to put something in the linter settings, this is my current linter config [based on a similar issue](https://github.com/SublimeLinter/SublimeLinter-phpcs/issues/3):

```
    "linters": {
        "phpcs": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "standard": ""
        }
    }
```

I can't use the solution described [here](https://github.com/SublimeLinter/SublimeLinter-phpcs/issues/30) as our theme name doesn't always match that of the project name, as well as plugin folders being unique for each plugin.

Is what I'm trying to do possible, or do I have to resort to just placing them in the project root each time we create a new project?

**Comment by kaste** [comment]
AFAIK the working dir is the key here

> PHP_CodeSniffer will look in the current directory, and all parent directories, ...

https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

By default the working dir is set to the open folder/project root (probably "project_name" in your example). You can set `working_dir` http://www.sublimelinter.com/en/stable/linter_settings.html#working-dir in the settings. Usually `${file_path}` but then you have a problem with new/unsaved files, `${file_path:$folder}` would add a fallback. Or you just exclude unsaved files `"excludes": ["<untitled>"]`.

**Comment by joemottershaw** [comment]
Thanks, I’m heading into the office now so I’ll try this out and see how it goes. I can’t see unsaved files being an issue here but the reason behind it makes sense if the working file doesn’t have a home yet.

**Comment by joemottershaw** [comment]
Just to confirm, this works as expected now, ended up just using `"working_dir": "${file_path}"`, thanks for the help!

**Comment by kaste** [comment]
💐
