### ISSUE TITLE
Custom standard not working seems to be using default php standards?

### ISSUE THREAD

**Issue by timrabbetts** [SublimeLinter/SublimeLinter-phpcs#50]
I have sublime text 3, sublime linter and sublime linter phpcs installed.  My projects settings looks like this.  But its not using the Drupal coding standards it looks like normal php standards?
`{
	"folders":
	[
		{
			"path": "/home/me/Projects/my_project"
		}
	],
        "settings": {
          "SublimeLinter.linters.phpcs.standard": 
            "/home/me/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml"
        }
}
`
But if I run this from the command line, I see the right sort of errors:
`phpcs --standard='/home/me/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml' DashboardController.php
`
Can you help advise what I am missing to get it to pick up the coding standards please?  Thanks

**Comment by kaste** [comment]
Take a look here https://github.com/SublimeLinter/SublimeLinter-phpcs/blob/master/README.md#per-project-standards 

Turns out that we don't have a setting "standard" so you need to use "args".

**Comment by timrabbetts** [comment]
This works thanks
{
	"folders":
	[
		{
			"path": "/home/me/Projects/myproj"
		}
	],
  "settings": {
    "SublimeLinter.linters.phpcs.args": "--standard='/home/me/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml'"
  }
}
