### ISSUE TITLE
problem with switch

### ISSUE THREAD

**Issue by unitydigital** [SublimeLinter/SublimeLinter-phpcs#53]
The switch and case are indented correctly, however I receive the following error.

phpcs: error
error - Line indented incorrectly; expected 8 spaces, found 12

![Screenshot from 2021-02-26 10-30-11](https://user-images.githubusercontent.com/79674296/109239272-d2737280-7820-11eb-8072-80f15f8bc1ba.png)

**Comment by kaste** [comment]
I need a reduced test case for this.  Ideally a public repo I can clone.  On the other hand does this work on the command line/Terminal as expected?

**Comment by unitydigital** [comment]
I never tried it on terminal. Is it possible to give me step by step instruction so I can generate everything you need? 
Then I can create a repo to clone.
I use ubuntu 20.04, Sublime 3.2.2

Regards

**Comment by kaste** [comment]
In the repo I just need a minimal, short source file plus the configuration.  Ideally I clone the repo, open the file, and see the error.

**Comment by kaste** [comment]
Close as stranded
