### ISSUE TITLE
Package linters HTML syntax?

### ISSUE THREAD

**Issue by processwired** [SublimeLinter/SublimeLinter-phpcs#7]
In pure HTML files with HTML syntax, I'm getting a following error: "No PHP code was found in this file and short open tags [...]" at the opening <html>.

By default, PHP Code Sniffer does not linter html files. I guess this plugin is configured to linter HTML files too in line "syntax = ('php', 'html', 'html 5')" in linter.py.

Is there a way to configure this? I don't like to edit linter.py, because that would not be upgrade-safe...

**Comment by vdh** [comment]
I've managed to work around the issue by added `"excludes": ["*.html"],` to my SublimeLinter config for phpcs

**Comment by corysimmons** [comment]
Yeah, linting .html automatically isn't cool or expected. Undo it please.

Thanks for the workaround @vdh
