### ISSUE TITLE
chdir error

### ISSUE THREAD

**Issue by Myrai** [SublimeLinter/SublimeLinter-phpcs#8]
I'm try with/without 
                "chdir": "${project}",
result own
SublimeLinter: chdir not set or invalid, using T:\Temp\scp07297\var\www\phalcon\assets 
SublimeLinter: phpcs: index.php ['D:\\php\\phpcs.bat', '--report=checkstyle', '-n', '--standard=PSR2'] 
SublimeLinter: phpcs output:
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.5.0">
</checkstyle>

**Comment by ajmichels** [comment]
It doesn't look like this is actually an issue. It has something to do with the base SublimeLinter package and is not specific to SublimeLinter-phpcs. They discuss the same issue in https://github.com/roadhump/SublimeLinter-eslint/issues/97#issuecomment-152740265

Based on the output that you included it doesn't look like this is having any impact on your linting and you can most likely just ignore it.

Is there something specific that you are having issues with that make you think this was a problem?

**Comment by ajmichels** [comment]
Closing this since I haven't received a response from the submitter.
