### ISSUE TITLE
Is it possible to set coding standards on a per project basis?

### ISSUE THREAD

**Issue by rpkoller** [SublimeLinter/SublimeLinter-phpcs#9]
Something i tried to accomplish but was unable to figure out based on the documentation yet. Let's say you have installed the coding standards for drupal and wordpress and then want to set the coding standard to drupalcs for a certain drupal project and wpcs for a wordpress project. cuz if you set the coding standard globally you are only able to set one of the two for files with the php extension. or am i missing something? Thanks r.

**Comment by corysimmons** [comment]
:+1:

**Comment by ajmichels** [comment]
Putting something like this in project settings seems to work for me:

```json
{
    "SublimeLinter": {
        "linters": {
            "phpcs": {
                "standard": "${project}/phpcs.xml"
            }
        }
    }
}
```

I am not sure what it uses `${project}` instead of `${project_path}` but that is an issue with SublimeLinter not this specific linter.

**Comment by ajmichels** [comment]
[Here is the documentation](http://www.sublimelinter.com/en/latest/settings.html#setting-tokens) for tokens (replacement strings) in SublimeLinter.

Unfortunately the documentation for this package is very lacking. [This line](https://github.com/SublimeLinter/SublimeLinter-phpcs/blob/master/linter.py#L32) of the linter however is where it is determined that you can override the `--standard` in your settings file.

**Comment by rizkysyazuli** [comment]
So i just installed the [Laravel standard](https://github.com/antonioribeiro/laravelcs). What's the correct way to use it?

```js
// project_name.sublime-project
{
    ...

    "settings": {
        // like this?
        "SublimeLinter.linters.phpcs.standard": "${folder}vendor/laravelcs/Standards/Laravel/ruleset.xml",
        // or this?
        "SublimeLinter.linters.phpcs.args": "--standard=${folder}vendor/laravelcs/Standards/Laravel/"
    }
}

```

Coz neither is working. The console still shows it's running with the default PSR2 standard.

```bash
SublimeLinter: #878 linter.py:1263: Running ...

  /Users/rizkysyazuli/Sites/project_name  (working dir)
  $ cat resources/views/backoffice/blog.blade.php | /Users/rizkysyazuli/.composer/vendor/bin/phpcs --report=emacs --standard=PSR2 --stdin-path=/Users/rizkysyazuli/Sites/project_name/resources/views/backoffice/blog.blade.php -
```

**Comment by kaste** [comment]
`"SublimeLinter.linters.phpcs.standard": "${folder}/vendor/laravelcs/Standards/Laravel/ruleset.xml",`

**Comment by kaste** [comment]
```
	"SublimeLinter.linters.phpcs.standard": "${folder}/vendor/laravelcs/Standards/Laravel/ruleset.xml",
```

works for me! Make sure you open the project file, not just the folder in Sublime
